### ISSUE TITLE
preset-typescript 3.0 w/ babel-loader

### ISSUE THREAD

**Issue by shilman** [storybookjs/presets#114]
### Proposal
- convert `@storybook/preset-typescript` to use `babel-loader` w/ `@babel/preset-typescript` (it currently uses `ts-loader`)
- make `@storybook/preset-typescript` a default install in `@storybook/cli`
- extra tweaks
  - check to see if it conflicts with other `.ts` rules in webpack and warn
  - warn and no-op if it's running with `@storybook/angular`, which can't use babel for some reason

### Rationale
- babel-loader is a common option and matches with what we do for `.js` files
- in `@storybook/react` projects we'll get `babel-plugin-react-docgen` "for free" which currently requires extra configuration (finishes https://github.com/storybookjs/storybook/issues/9837)
- similarly we can also inherit babel config for other non-react frameworks more easily

**Comment by ndelangen** [comment]
We should be able to re-use all logic for determining babel config by running `presets.apply('babel')` I think.

**Comment by kevin940726** [comment]
I just found out that `ts-loader` can be used with `babel-loader`, so that we can get both the babel ecosystem and ts type checking for free. I wonder if it makes sense?

**Comment by shilman** [comment]
@kevin940726 good thinking. we're currently using `fork-ts-checker-webpack-plugin` for that, which AFAIK is faster/better than `ts-loader` (but I could be wrong).

**Comment by mrmckeb** [comment]
Yes, I think @shilman is correct here - that's why that plugin was developed.

> which can't use babel for some reason
Is this only regarding TypeScript, or Babel in general?

**Comment by kroeder** [comment]
> warn and no-op if it's running with @storybook/angular, which can't use babel for some reason
and
> Is this only regarding TypeScript, or Babel in general? 

Because Angular needs to be compiled using the typescript compiler. It's because of the decorators that are differently compiled in babel. All you get from a compiled storybook-angular is a dependency injection error
