### ISSUE TITLE
ts-react examples question

### ISSUE THREAD

**Issue by 0x0006e** [storybookjs/presets#123]
hello! I was run [ts-react](https://github.com/storybookjs/presets/blob/master/examples/ts-react/src/components/Button/Button.tsx#L12) examples 

How let Button props  `variant` show ` "small" | "large"` in docs instead of screenshot below

![image](https://user-images.githubusercontent.com/18499153/78547089-13415200-7831-11ea-8049-bb4d3508ac3c.png)

**Comment by shilman** [comment]
dupe to https://github.com/storybookjs/storybook/issues/10311
