### ISSUE TITLE
SCSS preset doesn't use PostCSS

### ISSUE THREAD

**Issue by benedfit** [storybookjs/presets#131]
I don't believe the current SCSS preset makes use of PostCSS and ability to override the PostCSS settings with a custom config - https://storybook.js.org/docs/configurations/custom-postcss-config/. Could it?

**Comment by thibaudcolas** [comment]
Same question here. This feels a bit strange because Storybook’s built-in CSS support does use `postcss-loader`, for vendor prefixing in particular – so I’d have expected the same (and potentially extra configuration capabilities) from the SCSS preset.

https://github.com/storybookjs/storybook/blob/54b14cfe83742cf8198f40b4cd81200b8e58c6b2/lib/core/src/server/preview/base-webpack.config.ts#L65-L68

**Comment by benedfit** [comment]
I'm now using this along side `@storybook/addon-postcss` and it works as expected

**Comment by joebartels** [comment]
@benedfit could you share your main.js (and other relevant config files) please?

I'm using `preset-scss` with `addon-postcss` and my scss is still not being run through postcss 

I have tried a bunch of things, here is the most recent config that is not working:
```js
// .storybook/main.js
module.exports = {
    stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
    addons: [
        "@storybook/addon-links",
        "@storybook/addon-essentials",
        "@storybook/addon-postcss",
        {
            // hack to force postcss@8 use
            name: "@storybook/addon-postcss",
            options: {
                postcssLoaderOptions: {
                    implementation: require("postcss"),
                },
            },
        },
        "@storybook/preset-scss",
    ],
    webpackFinal: async (config) => {
        config.module.rules.push({
            test: /\.s[ca]ss$/,
            use: ["style-loader", "css-loader", "postcss-loader", "sass-loader"],
        });
        return config;
    },
```

perhaps order matters? I'm unable to find a working configuration :(
The overall application is nextjs, typescript, tailwindcss, and sass with module scss (component.module.scss) files

any suggestions are welcome :)

**Comment by LordZardeck** [comment]
I couldn't get @benedfit example working, but this worked for me in my `main.js`

```js
module.exports = {
    stories: [
        // Paths to the story files
        '../stories/**/*.stories.mdx',
        '../stories/**/*.stories.@(js|jsx|ts|tsx)'
    ],
    addons: [
        '@storybook/addon-links',
        '@storybook/addon-essentials',
        {
            name: '@storybook/addon-postcss',
            options: {
                postcssLoaderOptions: {
                    implementation: require('postcss')
                }
            }
        },
        {
            name: '@storybook/preset-scss',
            options: {
                cssLoaderOptions: {
                    modules: true,
                }
            }
        },
    ],
    webpackFinal: async (config) => {
        const cssRule = config.module.rules.find(rule => rule.test && rule.test.test('.css'));
        const sassRule = config.module.rules.find(rule => rule.test && rule.test.test('.scss'));
        const postCSSLoader = cssRule.use.find(config => config.loader && config.loader.indexOf('postcss-loader') > 0);

        sassRule.use.push(postCSSLoader);

        return config;
    },
};
```

**Comment by sharoneh** [comment]
any updates on this?

**Comment by smth** [comment]
Your solution worked for me @LordZardeck , but I've found that when I put a comment (`//`) in the SCSS I get an `Unknown word` error, as if PostCSS is trying to parse that comment.

**Comment by arlodesign** [comment]
@smth I tweaked @LordZardeck's config to have PostCSS run _after_ compiling Sass, which resolved the `//` issue for me. (I also tried using [`postcss-scss`](https://github.com/postcss/postcss-scss), but that gave me some issues in another part of my app.)

```js
  webpackFinal: async (config) => {
    const cssRule = config.module.rules.find(rule => rule.test && rule.test.test(".css"));
    const sassRule = config.module.rules.find(rule => rule.test && rule.test.test(".scss"));
    const sassLoaderIndex = sassRule.use.findIndex(
      ({ loader }) => loader && loader.includes("sass-loader")
    );
    const postCSSLoader = cssRule.use.find(
      ({ loader }) => loader && loader.includes("postcss-loader")
    );

    sassRule.use.splice(sassLoaderIndex, 0, postCSSLoader);

      return config;
  },

```

**Comment by PeterChen1997** [comment]
> @smth I tweaked @LordZardeck's config to have PostCSS run _after_ compiling Sass, which resolved the `//` issue for me. (I also tried using [`postcss-scss`](https://github.com/postcss/postcss-scss), but that gave me some issues in another part of my app.)
> 
> ```js
>   webpackFinal: async (config) => {
>     const cssRule = config.module.rules.find(rule => rule.test && rule.test.test(".css"));
>     const sassRule = config.module.rules.find(rule => rule.test && rule.test.test(".scss"));
>     const sassLoaderIndex = sassRule.use.findIndex(
>       ({ loader }) => loader && loader.includes("sass-loader")
>     );
>     const postCSSLoader = cssRule.use.find(
>       ({ loader }) => loader && loader.includes("postcss-loader")
>     );
> 
>     sassRule.use.splice(sassLoaderIndex, 0, postCSSLoader);
> 
>     return config;
>   },
> ```

This solution saves my day
