### ISSUE TITLE
It doesn't load any scss imports coming from node_modules

### ISSUE THREAD

**Issue by ivanji** [storybookjs/presets#143]
Hi guys - great preset, saved me lots of headaches. Just wondering why (of if I'm doing something wrong) it doesn't load scss files being imported in our global stylesheets from the node_modules. 

To be more specific: 
Our global stylesheet includes imports from individual Bootstrap modules (e.g @import '~bootstrap/scss/alert') but none of those are loaded. Is there an undocumented option we'd need to do or what's the reasoning behind this?

**Comment by andywd7** [comment]
@ivanji Did you sort this out? I'm having the exact same problem! Thanks

**Comment by ivanji** [comment]
@andywd7 We did - we only needed to add {auto: true} to the .scss rule, like this:
```
config.module.rules.push({
      test: /\.(scss)$/,
      use: [
        'style-loader',
        { loader: 'css-loader', options: { modules: { auto: true } } },

        'sass-loader'
      ]
    })

    return config
```

Hope it helps!
