### ISSUE TITLE
Gatsby.js with @storybook/preset-typescript

### ISSUE THREAD

**Issue by jlarmstrongiv** [storybookjs/presets#145]
Are there any examples on how to configure @storybook/preset-typescript with Gatsby.js?

The default Storybook with Gatsby config is available [here](https://www.gatsbyjs.org/docs/visual-testing-with-storybook/#add-typescript-support).  

I am trying to add mdx support with [addon-docs](https://www.npmjs.com/package/@storybook/addon-docs).  The alternative react-docgen-typescript-loader is looking for maintainers and does not support Storybook 5.x

Would appreciate any pointers 🙂 

Gatsby and Next.js presets are previously mentioned in https://github.com/storybookjs/presets/issues/95#issuecomment-579837857

**Comment by bsgreenb** [comment]
@jlarmstrongiv did you ever figure this one out?

**Comment by jlarmstrongiv** [comment]
@bsgreenb I did at one point 😄 The part of the solution I needed came from [tsdx](https://github.com/formium/tsdx/blob/master/templates/react-with-storybook/.storybook/main.js) and using `react-docgen-typescript-loader`.  

However, I was trying to use share the code amongst multiple frameworks, and decided using a prop like `tag` (from [reactstrap](https://reactstrap.github.io/components/navs/#app)) or `as` (from [styled-components](https://styled-components.com/docs/api#as-polymorphic-prop)) to pass in the Gatsby Link component, anchor tag, etc. fixed my portability problem.

**Comment by bsgreenb** [comment]
I got it working without any presets!  main.ts:
```
import { Configuration } from "webpack";

module.exports = {
  stories: [
    "../src/ui/**/*.stories.ts",
    "../src/ui/**/*.stories.tsx",
    "../src/ui/**/*.stories.mdx",
  ],
  addons: [
    "@storybook/addon-docs",
    "@storybook/addon-a11y",
    "@storybook/addon-actions",
    "@storybook/addon-controls",
    "@storybook/addon-links",
    "@storybook/addon-storysource",
    "@storybook/addon-toolbars",
    "@storybook/addon-viewport",
    "@storybook/addon-backgrounds/register",
  ],
  babel: {
    plugins: [
      "@babel/plugin-proposal-optional-chaining",
      "@babel/plugin-proposal-nullish-coalescing-operator",
      "@babel/plugin-proposal-class-properties",
      "babel-plugin-remove-graphql-queries",
      [
        "styled-jsx/babel",
        { optimizeForSpeed: true, plugins: ["styled-jsx-plugin-postcss"] },
      ],
    ],
  },
  webpackFinal: async (config: Configuration) => {
    // Transpile Gatsby module because Gatsby includes un-transpiled ES6 code.
    if (config?.module?.rules[0]) {
      config.module.rules[0].exclude = [/node_modules\/(?!(gatsby)\/)/];
    }

    // Prefer Gatsby ES6 entrypoint (module) over commonjs (main) entrypoint
    if (config?.resolve) {
      config.resolve.mainFields = ["browser", "module", "main"];
    }

    return config;
  },
};
```
