### ISSUE TITLE
Storybook fails to find CRA preset in a monorepo with Yarn 2/PNP

### ISSUE THREAD

**Issue by seniorquico** [storybookjs/presets#161]
I have a monorepo with multiple packages and Yarn 2/PNP. One package is based on CRA, and I added Storybook 6. Specifically, I'm using Yarn 2.1.1 and Storybook 6.0.7. Unfortunately, the following error occurs trying to start Storybook:

> @storybook/react v6.0.7
>
> => Loading presets
>   Failed to load preset: {"name":"@storybook/preset-create-react-app","type":"presets"} on level 1
> TypeError: Cannot read property 'packageLocation' of null
>     at Object.exports.getReactScriptsPathWithYarnPnp (D:\....\.yarn\$$virtual\@storybook-preset-create-react-app-virtual-376e0be20a\0\cache\@storybook-preset-create-react-app-npm-3.1.4-7672914a03-0991e0944c.zip\node_modules\@storybook\preset-create-react-app\dist\helpers\getReactScriptsPath.js:71:125)

The preset tries to find `react-scripts` using the following PNP API call:

```ts
const { packageDependencies } = pnpApi.getPackageInformation({
  name: null,
  reference: null,
});
```

[(link to source)](https://github.com/storybookjs/presets/blob/0a8ce5616fd9a9a77b3296d151221152c07dbbff/packages/preset-create-react-app/src/helpers/getReactScriptsPath.ts#L68-L72)

I'm not too familiar with the PNP internals, but I did some poking around the source code and the docs and found this:

> Note that one package locator is different from the others: the top-level locator (available through `pnp.topLevel`, cf below) sets both `name` and `reference` to null. **This special locator will always mirror the top-level package (which is generally the root of the repository, even when working with workspaces**).

Dropping into a Node shell with a cwd of the CRA workspace, I was able to confirm that the PNP API calls return the top-level dependencies in my monorepo, not those of the CRA workspace. As a quick hack/workaround, I added a `react-scripts` dependency to the top-level `package.json`, and then Storybook started as expected.

It appears that the current PNP API usage works if the CRA package is not in a workspace.

**Comment by chrislambe** [comment]
Also experiencing this error, but I was unable to get @seniorquico's workaround (installing `react-scripts` in the top-level `package.json`) to resolve the issue.
