### ISSUE TITLE
preset-create-react-app is unable to find react-scripts in a Yarn 2 (berry) monorepo when nodeLinker is set to node-modules

### ISSUE THREAD

**Issue by chrislambe** [storybookjs/presets#168]
Initially I thought my issue was the same as #161 but that turns out not to be the case.

**Context**
I have a Yarn 2 monorepo where `nodeLinker` is set to `node-modules` (due to VS Code's lack of support of zipped modules). Multiple workspaces in the monorepo are using `react-scripts` and Storybook.

**Problem**
When running Storybook in a workspace from the project root, the CRA preset is unable to find the `react-scripts` package:
```
$ yarn workspace workspace-a storybook
info @storybook/react v6.0.21
info
info => Loading static files from: /Volumes/Storage/Documents/Projects/storybook-cra-monorepo-issue/packages/workspace-a/public .
info => Loading presets
info => Loading presets
info => Loading config/preview file in "./.storybook".
info => Loading config/preview file in "./.storybook".
info => Adding stories defined in ".storybook/main.js".
ERR! Failed to resolve a `react-scripts` package.
info => Using default Webpack setup.
19% building 81/92 modules 11 active /Volumes/Storage/Documents/Projects/storybook-cra-monorepo-issue/node_modules/ansi-html/index.js
```

**What's going wrong**
I stepped through the preset code and found that `process.versions.pnp` is *not* set. I assume this is due to the use of `nodeLinker: node-modules`? Whatever the reason, this causes the preset to look for the `react-scripts` binary in the `node_modules` directory of the workspace ([source](https://github.com/storybookjs/presets/blob/master/packages/preset-create-react-app/src/helpers/getReactScriptsPath.ts#L6)). However, with two workspaces using `react-scripts`, Yarn moves the package (and thus the binary) up into the project root `node_modules` directory so the preset is unable to find it. Eventually it falls through to a `require.resolve('react-scripts');` call, which fails.

**Very temporary workaround**
If you've come across this issue and need to get unblocked, the easiest way I've found is to just symlink the `react-scripts` binary into the workspace. You may need to create the `node_modules/.bin` directory in the workspace manually:

```shell
mkdir -p packages/workspace-a/node_modules/.bin
$(cd packages/workspace-a/node_modules/.bin ; ln -s ../../../../node_modules/.bin/react-scripts .)
```

This could easily get wiped out during package installation removal so it's not really a long term solution.

**Minimal repro**
I put together a minimal reproduction in a project which you can find here:
https://github.com/chrislambe/storybook-cra-preset-monorepo-issue

**Comment by chrislambe** [comment]
Based on [the documentation](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders) I would actually expect `require.resolve('react-scripts');` to succeed. I would expect that it would look like this:
```
/path/to/project/packages/workspace-a/node_modules/react-scripts # fail
/path/to/project/packages/node_modules/react-scripts # fail
/path/to/project/node_modules/react-scripts # success
```
Does anyone know why that wouldn't be the case here?

**Comment by chrislambe** [comment]
I did a little more reading and I think I misunderstood the `resolve` algorithm. It seems that the algorithm sees `node_modules` in the workspace and stops there to look for `react-scripts`. If it doesn't find it, it won't keep searching upwards for another `node_modules` dir. That said, a slightly more automated way to implement the workaround is to add this to the workspace `package.json`:
```
"postinstall": "ln -s ../../../node_modules/.bin node_modules"
```
The `source` path will depend on where your workspace lives in relation to the monorepo root.

**Comment by mrmckeb** [comment]
I think we need to resolve `node_modules` from the users project root, and that might solve the issue. Would you be happy to try and that out and let us know if it works?

`require.resolve('react-scripts', { paths: ['/path/to/project/root'] })`

**Comment by fraindz** [comment]
Here is what we tried,

- require.resolve('./react-scripts', { paths: ['/path/to/project/root'/node_modules/.bin'] }) -- **this works**
- require.resolve('./react-scripts', { paths: ['/path/to/project/root'/node_modules'] }) -- **does not work**
- require.resolve('./react-scripts', { paths: ['/path/to/project/root'] }) -- **does not work**

Trying to resolve with 'react-scripts'(without using ./), does not work for any of the options above.

**Comment by dannycoates** [comment]
`require.resolve('react-scripts')` throws a `MODULE_NOT_FOUND` error because it's package.json doesn't include a `"main"` entrypoint.

I find the next best way to get its root is `path.dirname(require.resolve('react-scripts/package.json'))`
