### ISSUE TITLE
Problem with ejected create-react-app ap

### ISSUE THREAD

**Issue by annguyen-dev** [storybookjs/presets#169]
### Problem with ejected create-react-app ap
I ran the `eject script` in  my app created with create-react-app and then receive the `Failed to resolve a `react-scripts` package.`(i need to custom my app, my client doesn't like cra)

### Steps to reproduce the behavior

1. npm run eject
2. npm storybook

**Comment by mrmckeb** [comment]
Hi @annguyen-dev, this preset is designed to work with Create React App - an ejected app is no longer a `react-scripts` project, and you'll no longer be able to use this preset sorry. You could look at the source code of the preset and modify it to work for your project as an option.

I'm part of the CRA team and also maintain this preset. We recommend never ejecting, unless you absolutely need to, for reasons like this.

**Comment by mrmckeb** [comment]
Closing this one off because this isn't a supported usecase today.
