### ISSUE TITLE
Ant Design preset

### ISSUE THREAD

**Issue by shilman** [storybookjs/presets#35]
Apparently there is some work required to get Ant Design working with Storybook. If we could package that into a preset, it would help people use the tools together.

Here's what that would look like:
- [ ] `@storybook/preset-ant-design` package under `packages/preset-ant-design`
- [ ] Copy structure of an existing preset (e.g. `preset-typescript`)
- [ ] Include README and sample storybook

Presets reference docs here: https://storybook.js.org/docs/presets/introduction/

**Comment by beizhedenglong** [comment]
@shilman I can help with this issue.

**Comment by Zaccc123** [comment]
Hey @shilman, sorry for being late. I just tested on this on my project and it works awesome! I needed some extra setup on the `options` and it covered perfectly! Kudos to you and @beizhedenglong. 

I added into documentation for this: https://github.com/storybookjs/storybook/pull/8254


Just FYI, the preset i used.
```
// My preset.js
const theme = require('../configs/anyDateTime.theme');

module.exports = [
  {
    name: '@storybook/preset-ant-design',
    options: {
      lessOptions: {
        modifyVars: theme,
        javascriptEnabled: true
      }
    }
  }
];
```

**Comment by shilman** [comment]
Closing this! Great job guys!!!
