### ISSUE TITLE
[preset-storysource] Not published to NPM

### ISSUE THREAD

**Issue by raulfdm** [storybookjs/presets#39]
I tried to install `@storybook/preset-storysource`, but apparently isn't published.

```
$ yarn add @storybook/preset-storysource -D
yarn add v1.17.3
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.com/@storybook%2fpreset-storysource: Not found".
```

![Screenshot 2019-10-12 at 10 19 17](https://user-images.githubusercontent.com/12464600/66697879-c9403f00-ecd9-11e9-9be4-edffb8e455ac.png)

Is there a way I can help to solve this issue?

**Comment by shilman** [comment]
We're going to move this into the addon--it doesn't need its own package. If you'd like to do that, I'd def review a PR for that.

**Comment by jerriclynsjohn** [comment]
@shilman is this part of the addon package itself, If that's the case then we should update the readme as it mentions `@storybook/preset-storysource`

**Comment by shilman** [comment]
@jerriclynsjohn See my PR: https://github.com/storybookjs/presets/pull/43

**Comment by doublejosh** [comment]
Looks like the type definitions are also not published...
`An unexpected error occurred: "https://registry.npmjs.org/@types%2fstorybook__addon-storysource: Not found"`
