### ISSUE TITLE
preset-create-react-app yarn workspaces

### ISSUE THREAD

**Issue by maniax89** [storybookjs/presets#50]
as part of yarn workspaces i have hoisted all of my dev dependencies to the project root (rather than individual packages. however our storybook build is part of only one of our packages

would it be possible to modify the way that `preset-create-react-app` consumes `scriptsPackageName` to not assume `process.cwd()` when resolving? would be nice to do
```
scriptsPackageName: '../../../node_modules/.bin/react-scripts'
```

**Comment by mrmckeb** [comment]
Hi @maniax89, sorry for the slow reply.

I'm currently using Yarn workspaces with CRA and this preset and it's working as expected. 

Are you using a custom scripts package? Can you provide any more information?

`scriptsPackageName` should not point to a file in `.bin`, but instead the package folder.

**Comment by maniax89** [comment]
I am not using a custom scripts package. One of the issues with a mono repo is duplicate dev dependencies throughput the repository. So instead of specifying `react-scripts` in every package's `package.json`, I only specify it once in the project root.

However, since my storybook build is run from one of the packages (not project root) via something like `yarn workspace my-package run storybook` there's no way for me to reference the project root `react-scripts` package, even if I point directly to the `node_module` (sorry my example pointed at the `.bin` location)

Everything works fine if I specify the `react-scripts` dev dependency in the package that uses it, was just asking for an enhancement to support when we hoist those dev dependencies to the project root.

I'll see if I can produce an example repo to showcase what I'm trying to do

**Comment by mrmckeb** [comment]
@maniax89 If you're doing that, then I think that's going to be hard for us to support - as you're not using this monorepo in the expected way.

Monorepos dedupe, so this shouldn't be an issue if they're all at the same version. You can use features like Yarn's `resolutions` to help here. Let me know if you want some tips on that :)

That being said, your case should be solvable regardless - have you tried this?
```
const path = require("path");
module.exports = [
  {
    name: "@storybook/preset-create-react-app",
    options: {
      scriptsPackageName: path.resolve("../../../node_modules/react-scripts"),
    }
  }
];
```

**Comment by maniax89** [comment]
when i attempt the above, i see
```
> yarn run storybook
yarn run v1.17.3
$ start-storybook --ci --port=9002
info @storybook/react v5.3.0-alpha.38
info
info => Loading presets
info => Loading presets
info => Loading custom addons config.
WARN A `scriptsPackageName` was provided, but couldn't be resolved.
ERR! Failed to resolve a `react-scripts` package.
info => Using default Webpack setup.
```

any number of `../` doesn't seem to work properly

**Comment by mrmckeb** [comment]
Are you able to share this project @maniax89? Even privately? 

Can you share your current config file here?

**Comment by mrmckeb** [comment]
Hi @maniax89, did you get this working? If so, can we close this one off? Thanks!

**Comment by maniax89** [comment]
Sorry - I haven't gotten back around to this since the initial discussion so I'm going to close it for now and reopen if and when I get a reproducible repo example. Thanks for checking in on this

**Comment by salieri** [comment]
Related to #112
