### ISSUE TITLE
preset-create-react-app fails to resolve react-scripts in RushJS monorepo with PNPM

### ISSUE THREAD

**Issue by dstaver** [storybookjs/presets#58]
I get the following error:
`stack: "Error: Cannot find module 'monorepodir/libraries/ui/node_modules/config/webpack.config'\n" +`

I can fix it by manually commenting out line 27-39 in 
`node_modules/@storybook/preset-create-react-app/helpers/getReactScriptsPath.js`

Seems like `/node_modules/.bin/react-scripts` isn't symlinked like the preset expects which makes it resolve to an incorrect directory

**Comment by mrmckeb** [comment]
Hi @dstaver, we haven't yet tested this against PNPM / Yarn PNP. 

Are you able to provide a repro repo? I can then take a look and try to resolve this :)

This preset does work in monorepos with Yarn, when _not_ using PNP.

**Comment by qin-guan** [comment]
are there any updates on this issue?

**Comment by mrmckeb** [comment]
Hi @qin-guan, if you can provide a reproduction repository I can try to take a look into this one.

**Comment by qin-guan** [comment]
Hi @mrmckeb, sorry for the late reply.
I have made a repository [here](https://github.com/qin-guan/pnpm-storybook). Thanks :)

**Comment by qin-guan** [comment]
@mrmckeb, any developments regarding this?

**Comment by iPzard** [comment]
Having the same issue, thanks for looking into this!

**Comment by qin-guan** [comment]
@iPzard can you see if the error can be reproduced with the repository I provided?

**Comment by talentlessguy** [comment]
Same issue, have to install dependencies with `yarn` now ;(

**Comment by remorses** [comment]
This will be solved by #166, it was really a dumb change
