### ISSUE TITLE
preset-create-react-app v1.3.0 breaks SASS support

### ISSUE THREAD

**Issue by daniel-ac-martin** [storybookjs/presets#60]
v1.3.0 of preset-create-react-app appears to break SASS support. (I've been forced to downgrade to v1.2.0 anyway.)

I installed CRA and then Storybook over the top giving me v1.2 at the time. (Though please note this is with Typescript support.) Everything worked but after deleting my `package-lock.json` and `node_modules/` and running `npm install` (and so pulling down the new version, v1.3.0) I had the situation in which:
1. CRA (npm start) still worked with SCSS.
2. Storybook (npm run storybook) failed with an error like below:
   > ERROR in ./src/index.scss 2:0
Module parse failed: Unexpected character '@' (2:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

Pinning to v1.2 and reinstalling would appear to fix the problem leading me to suspect there is a bug in the new version.

I coudn't see anything obviously wrong in the webpack config that I extracted. (It has an entry for handling `.scss` files.) That said, I'm not an expert in webpack.

I did notice that the final entry in the `oneOf` array (that appears to contain the rule for handling `.scss` files) has been replaced with an empty object. The old version didn't appear to relate to SASS in any way though. Is it possible that the empty object would invalidate the entire array and so wipe out the SASS handling rule? The previous version of this object was as follows:
```js
{
  loader: '/path/to/my/project/node_modules/file-loader/dist/cjs.js',
  exclude: [
    /\.(js|mjs|jsx|ts|tsx)$/,
    /\.html$/,
    /\.json$/,
    /\.(ejs|mdx)$/
  ],
  options: { name: 'static/media/[name].[hash:8].[ext]' }
}
```

**Comment by shilman** [comment]
released in 1.3.1

**Comment by mrmckeb** [comment]
Sorry about this one @daniel-ac-martin, we've added a test to cover this in future.

We're working on cleaning up the presets a little more. An issue @shilman and I uncovered recently is the root cause of this, but we will do our best to ensure there are workarounds in CRA for the meantime.

**Comment by daniel-ac-martin** [comment]
Thanks for fixing this so quickly!

**Comment by mrmckeb** [comment]
Sorry for breaking it!
