### ISSUE TITLE
CRA preset: triconfig compatibility

### ISSUE THREAD

**Issue by shilman** [storybookjs/presets#71]
CRA preset check [relies on the old `presets.js` configuration](https://github.com/storybookjs/presets/blob/master/packages/preset-create-react-app/src/helpers/checkPresets.ts#L12)

This should be updated to also handle Tri-config. Also @ndelangen do we need some kind of helper function for this that handles both cases for addons to use?

**Comment by shilman** [comment]
Here's how it's handled in the built-in preset:

https://github.com/storybookjs/storybook/pull/9075/commits/51c9b2a38485d46b893773099ecdf2570f541b8a

**Comment by shilman** [comment]
Can confirm that Storybook changes, presumably those in https://github.com/storybookjs/storybook/pull/9075 have broken the preset, both in Triconfig mode (`main.js`) and ALSO in traditional configuration mode (`config.js`/`presets.js`).

To reproduce:
1) Follow instructions in https://gist.github.com/shilman/bc9cbedb2a7efb5ec6710337cbd20c0c
2) Observe no prop tables
3) Run with `--debug-webpack` to show that no TS loader was added
4) Downgrade to `5.3.0-beta.16` and re-run, observe prop tables

**Comment by mrmckeb** [comment]
Thanks @shilman, I can take a look at this over this week - alongside the cleanup/quality work.

This is going to be part of 5.3.0?

**Comment by shilman** [comment]
@mrmckeb Thank you! It's already part of 5.3 and breaking users since beta.16 😁

**Comment by mrmckeb** [comment]
OK, will look tonight if possible!

**Comment by danfinch100** [comment]
Hi - I tried downgrading to 5.3.0-beta.16 but still can't see the props. Could you post a basic package.json with the last stable (non-beta) version where this is working? Even better would be a starter project where the configuration (i.e. Tri config or traditional) is clear. Thanks

**Comment by shilman** [comment]
@danfinch100 follow this with `beta.15` or below: https://gist.github.com/shilman/bc9cbedb2a7efb5ec6710337cbd20c0c

**Comment by danfinch100** [comment]
Great, that works - thanks. Also, should point out that the comments i.e. 'The world's most _basic_ button' weren't working either but are with beta.15  ... thats both:

npx -p @storybook/cli@5.3.0-beta.15 sb init --story-format=csf-ts

and

yarn add @storybook/addon-docs@5.3.0-beta.15 --dev
