### ISSUE TITLE
TypeScript Preset 1.2.0 not working w/ HTML framework

### ISSUE THREAD

**Issue by darondel-yoobic** [storybookjs/presets#79]
After upgrading the TypeScript Preset from 1.1.0 to 1.2.0, we got a lot of errors (unexpected token). The TypeScript code cannot be parsed anymore. You can reproduce by cloning [this repository](https://github.com/darondel/storybook-html-playground):

- Current version uses 1.1.0 => it works.
- Try to upgrade to 1.2.0 => it fails.

Note that if I uses the 1.1.0 version with the new beta version of Storybook (5.3), it fails as well.

Something is missing from my configuration?

**Comment by shilman** [comment]
@karolisgrinkevicius Would you mind looking into this? The difference between 1.1 and 1.2 is the `fork-ts-checker-webpack-plugin` you added: https://github.com/storybookjs/presets/pull/56

**Comment by karolisgrinkevicius** [comment]
@shilman sure, I will look into this.

**Comment by karolisgrinkevicius** [comment]
So the bug actually lies in this recent commit: https://github.com/storybookjs/presets/commit/f71637c0385d6cdd452792e07bb85afb25967561. Specifically `include` init. Without it being initialized to an empty array it works just fine.

**Comment by T0MASD** [comment]
@darondel-yoobic thanks for providing the test repo and thanks @karolisgrinkevicius for identifying the issue. I propose instead of overwriting the existing includes (that may have come from webpack config) to append them, like it's done with other options using rest parameter.

https://github.com/storybookjs/presets/compare/master...T0MASD:append_includes

**Comment by darondel-yoobic** [comment]
@shilman Is there any update on this issue?

**Comment by shilman** [comment]
@darondel-yoobic merged the fix ie #106 and released as 1.2.1. Also released 2.0.0 which includes the fix to https://github.com/storybookjs/storybook/issues/8337

**Comment by darondel-yoobic** [comment]
@shilman Works like a charm, thanks!
