### ISSUE TITLE
preset-create-react-app: adding the configDir for the include array breaks when using exclude

### ISSUE THREAD

**Issue by joeycozza** [storybookjs/presets#80]
https://github.com/storybookjs/presets/blob/dc3ae592895af3c60bf679f17bc8bf3e77c7d690/packages/preset-create-react-app/src/helpers/processCraConfig.ts#L128

I have a bit of an abnormal scenario.

I forked create-react-app, and in my babel-loader rule, I use an `exclude` function instead of the `include` array. 

But this preset adds in configDir in the includes array, which then messes me up. 

According to [webpack's docs](https://webpack.js.org/configuration/module/#rule-conditions)

> When using multiple conditions, all conditions must match.

So my exclude function is only applying to files inside `.storybook`.

To solve my issue, I find my special babel-loader with the exclude function, and run 
```javascript
delete babelLoader.include
```

### Why am I bringing this up?
1. In case someone else who has forked cra is having issues
2. We could potentially do a check in the processCraConfig.ts file. If using exclude, and NOT include then maybe we could log a big warning to the console?

I'm willing to make a PR for that, if you think it is valuable.
Also, if you'd like, I could maybe add this note to the preset-create-react-app Advanced Usage readme docs.

Let me know if you'd like me to take any of that on.

**Comment by shilman** [comment]
Gonna let @mrmckeb field this one 😄

**Comment by mrmckeb** [comment]
Hi @joeycozza, a lot of our users - including myself - have forks of CRA.

While the preset caters for 99% of those cases, there may be cases where you need to still provide additional config... and I think this is one of those.

As I think you've found already, you can create a `webpack.config.js` file for Storybook, you'll be able to intercept the config. The config will already have been processed by the preset, so all you'll need to do is find the rule you need and modify it.

My personal opinion on this is that if people are comfortable modifying `react-scripts` and the Webpack config, then it's not unfair to expect that people to also manage this config... but as we do some very minor changes, I also understand that we could explain that better.

I think a warning is fair, but it would have to cover all cases where we intercept/add to the include function.

Also keep in mind that we can't guarantee the preset will work if the Storybook config folder is not included.

**Comment by shilman** [comment]
@mrmckeb I agree. I don't think we should be on the hook for forks and weird corner cases. Warnings are cool if we can do them in generic ways! 💯

**Comment by joeycozza** [comment]
Yeah, I totally understand and agree.

I'll make a PR that adds a note to the README under the Advanced Usage section that "the preset will add the storybook config directory to the include Condition of cra's webpack babel-loader" or something to that effect.

I don't have time today to look into a good "generic, all cases" warning for this kind of issue. Maybe after the holidays I'll jump on that.

**Comment by joeycozza** [comment]
https://github.com/storybookjs/presets/pull/81

**Comment by mrmckeb** [comment]
Thanks @joeycozza, sorry for the slow reply - holidays...

**Comment by joeycozza** [comment]
No problem at all. Just happy to possibly help someone else in this rare scenario.
