### ISSUE TITLE
Question: JSX in stories

### ISSUE THREAD

**Issue by steveoh** [storybookjs/presets#94]
Are you unable to have jsx in stories with the CRA preset?

```
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

This is thrown from this [story](https://github.com/agrc-widgets/kitchen-sink/blob/master/packages/layer-selector/LayerSelectorContainer.stories.js#L10)

It appears to work without the preset and the base config

**Comment by shilman** [comment]
@steveoh As far as I can tell, that's not a CRA project. Why would you add the CRA preset?

**Comment by steveoh** [comment]
We added the CRA preset since we use the components in this monorepo in CRA's. We were hoping to have the same webpack/babel configurations in the stories as the consuming application. Are we in left field with this thinking?

**Comment by shilman** [comment]
I wouldn't expect it to work, since the preset expects that it's being run in a CRA context.

But I think what you're looking for is a component library that works like CRA but is not CRA and is used in CRA. And maybe @mrmckeb has suggestions on how best to achieve that?

**Comment by steveoh** [comment]
Thanks any tips would be very much appreciated!

**Comment by mrmckeb** [comment]
Hi @steveoh, this is a limitation of CRA - we don't support what you're trying to achieve (currently).

I also run a project in a monorepo, with shared components. For that project, we treat it like any library - it has build steps, and CRA loads the built version.

This is something we might address in v4, but I'm not sure at this stage.

**Comment by steveoh** [comment]
Yeah we treat it like a library also with build steps and CRA loading the built output. We just added the babel create react app preset (we were using react and env prior) and now we're reading about node_env yada yada. I'm not sure if using the preset is a rabbit hole or not yet...

**Comment by mrmckeb** [comment]
I don't think it'll be a rabbit hole @steveoh, you will need to handle SVGs too if you want to use those (or you can just inline them as components)... but otherwise that's exactly what I've had on a project for 9 months and it has been stable.

**Comment by steveoh** [comment]
Can you link me to it as an example?
