### ISSUE TITLE
`preset-typescript` cannot find module 'typescript'

### ISSUE THREAD

**Issue by kevinehosford** [storybookjs/presets#99]
I'm trying to set up TypeScript with a new project. Here is an example repo that exhibits the problem I'm running into: https://github.com/kevinehosford/test-preset-typescript

I followed the instructions to add `preset-typescript`; however, running `storybook` fails with the following error:

```
info @storybook/react v5.3.9
info
info => Loading presets
info => Loading presets
info => Adding stories defined in ".storybook/main.js".
ERR! Error: Cannot find module 'typescript'
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:33:19)
ERR!     at ForkTsCheckerWebpackPlugin.validateTypeScript
```

Is there some configuration step I've missed?

**Comment by kevinehosford** [comment]
I was able to fix this on the new setup.

**Comment by maxtotheguenther** [comment]
@kevinehosford  I have the same problem. How did you fix it?
